name: protovae
# channels:
#   - anaconda
#   - pytorch
#   - defaults
dependencies:
  - python=3.8.12
  - numpy=1.19
  - pandas
  - scipy
  - scanpy
  - anndata
  - scikit-learn
  - pytorch=1.7.1
  - torchvision=0.8.2
  - scvi-tools
  - celltypist
  - matplotlib=3.5.1
  - seaborn
  - umap-learn