name: protoCloud
channels:
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - numpy>=1.26.4
  - pandas>=2.2.2
  - scipy>=1.13.1
  - scanpy>=1.10.2
  - anndata>=0.10.8
  - scikit-learn
  - pytorch>=1.12.1
  - torchvision>=0.13.1
  - matplotlib
  - matplotlib_venn
  - seaborn
  - umap-learn
